"""add_categories_table_and_skill_order

Revision ID: 3b6f3587b1f1
Revises: 82f391949f6b
Create Date: 2026-05-04 21:40:23.981789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b6f3587b1f1'
down_revision: Union[str, Sequence[str], None] = '82f391949f6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('label_fr', sa.String(length=100), nullable=False),
    sa.Column('label_en', sa.String(length=100), nullable=False),
    sa.Column('accent', sa.String(length=20), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.add_column('skills', sa.Column('order', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('skills', 'order', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skills', 'order')
    op.drop_table('categories')
    # ### end Alembic commands ###
