"""change stack column to JSON

Revision ID: acffe357c126
Revises: 6f695d4227ad
Create Date: 2026-05-04 20:48:37.050212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'acffe357c126'
down_revision: Union[str, Sequence[str], None] = '6f695d4227ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE projects ALTER COLUMN stack TYPE JSON USING to_json(stack)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'stack',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=False)
    # ### end Alembic commands ###
